No GPUs found. Using CPU.
Starting LSM training with parameters:
  Window size: 64
  Batch size: 8
  Epochs: 100
  Test size: 0.2
  Embedding dim: 64
  Reservoir type: hierarchical
  Random seed: 42
  Reservoir config: {'scales': [{'units': 64, 'sparsity': 0.1, 'time_constant': 0.05, 'frequency_range': [0.5, 1.0]}], 'global_connectivity': 0.05}
================================================================================
LIQUID STATE MACHINE TRAINING - HIERARCHICAL RESERVOIR
================================================================================
Loading data...
Downloading dataset from https://huggingface.co/datasets/google/Synthetic-Persona-Chat/resolve/main/data/Synthetic-Persona-Chat_train.csv
Dataset downloaded and cached to dataset_cache.csv
Loaded dataset with 8938 rows and columns: ['user 1 personas', 'user 2 personas', 'Best Generated Conversation']
Parsed 29 dialogue sequences
Fitting tokenizer...
Converting sequences to embeddings...
Training data shape: X=(23, 64, 64), y=(23, 64)
Test data shape: X=(6, 64, 64), y=(6, 64)
Data loaded: Train=(23, 64, 64), Test=(6, 64, 64)
Starting LSM training...
Building hierarchical reservoir model...
Building CNN model...
Models built successfully!
Reservoir type: hierarchical
Reservoir output shape: (None, 64)
CNN input shape: (None, 64, 64, 1)
CNN output shape: (None, 64)
Creating training waveforms...
Converting 23 sequences to waveforms...
Processing batch 1/3
Error executing command 'train': Exception encountered when calling SparseDense.call().

<tf.Tensor 'scale_0_sparse/Const:0' shape=(64, 64) dtype=float32> is out of scope and cannot be used here. Use return values, explicit Python locals or TensorFlow collections to access it.
Please see https://www.tensorflow.org/guide/function#all_outputs_of_a_tffunction_must_be_return_values for more information.

<tf.Tensor 'scale_0_sparse/Const:0' shape=(64, 64) dtype=float32> was defined here:
    File "/content/LiquidState/main.py", line 271, in <module>
    File "/content/LiquidState/main.py", line 256, in main
    File "/content/LiquidState/main.py", line 61, in train_command
    File "/content/LiquidState/train.py", line 465, in run_training
    File "/content/LiquidState/train.py", line 313, in train
    File "/content/LiquidState/train.py", line 80, in build_models
    File "/content/LiquidState/advanced_reservoir.py", line 428, in create_advanced_reservoir
    File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
    File "/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py", line 936, in __call__
    File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
    File "/usr/local/lib/python3.11/dist-packages/keras/src/ops/operation.py", line 58, in __call__
    File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 156, in error_handler
    File "/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py", line 814, in symbolic_call
    File "/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py", line 1130, in compute_output_spec
    File "/usr/local/lib/python3.11/dist-packages/keras/src/ops/operation.py", line 100, in compute_output_spec
    File "/usr/local/lib/python3.11/dist-packages/keras/src/backend/tensorflow/core.py", line 240, in compute_output_spec
    File "/content/LiquidState/advanced_reservoir.py", line 112, in call
    File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
    File "/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py", line 866, in __call__
    File "/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py", line 1458, in _maybe_build
    File "/usr/local/lib/python3.11/dist-packages/keras/src/layers/layer.py", line 232, in build_wrapper
    File "/content/LiquidState/reservoir.py", line 38, in build
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/ops/weak_tensor_ops.py", line 142, in wrapper
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/constant_op.py", line 276, in constant
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/constant_op.py", line 291, in _constant_impl
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/ops.py", line 289, in _create_graph_constant
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/func_graph.py", line 614, in _create_op_internal
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/ops.py", line 2705, in _create_op_internal
    File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/ops.py", line 1200, in from_node_def

The tensor <tf.Tensor 'scale_0_sparse/Const:0' shape=(64, 64) dtype=float32> cannot be accessed from here, because it was defined in FuncGraph(name=scratch_graph, id=134711719667904), which is out of scope.

Arguments received by SparseDense.call():
  â€¢ inputs=tf.Tensor(shape=(1, 64), dtype=float32)